### PR TITLE
Feature/sabbir alert new final

### PR DESCRIPTION
**Pull request by Sabbir45ali**
Hi @Subhratanu @EmrysILIO1710  ,

Please approve and merge this PR.

Features added or modified- 

1. Alert for new users to complete their profile.
2. New modal for remainder for complete user's profile .

Ref:
image

Alert on top of story

image

after close the alert

Following task- Changing to light mode of alert.

cc- @gitterarka @soumi-27

### CODE REVIEW

**Comment by Subhratanu** [comment]
Hi @Sabbir45ali 

For this task why 23 files got changed? Could you please justify, afterwards I'll approve.

Cc: @EmrysILIO1710

**Comment by Subhratanu** [comment]
It have merge conflicts please resolve that first.

**Comment by Sabbir45ali** [comment]
Hi, @Subhratanu  @EmrysILIO1710 

Conflict resolved .

**Review by Subhratanu — APPROVED** [review]
Approved & Merged!

Thanks

**Pull request merged**
