### PR TITLE
Created Search Bar and made some necessary changes.

### PR DESCRIPTION
**Pull request by EmrysILIO1710**
Hi @Subhratanu ,

Please approve and merge this PR.

Features added or modified-
1. Modified navbar, removed home, reels, groups and added search bar functionality.
2. Changed profile cover default background to transparent.
3. Modified width of follow button in right sidebar.
4. Removed change background garbage code from feed page.

Ref:
Screenshot 2024-03-27 011206

Following task- no remaining task pertaining search bar.

cc @gitterarka @Sabbir45ali @soumi-27

### CODE REVIEW

**Review by Subhratanu — CHANGES_REQUESTED** [review]
Hi @EmrysILIO1710 ,

Please give a proper name for searchRequest2.jsx instead of it. It's not recommended to end a component name by numeric value.

**Comment by EmrysILIO1710** [comment]
Hi @Subhratanu ,

Required changes successfully made.
Please approve and merge this PR.

**Comment by Subhratanu** [comment]
Hi @EmrysILIO1710 

Could you please mention the updated the component name?

**Comment by EmrysILIO1710** [comment]
Hi @Subhratanu ,
I have deleted <SearchResults2 /> and copied the code in <SearchResults />, which was previously unused.

**Comment by EmrysILIO1710** [comment]
Hi @Subhratanu ,
I have deleted SearchResults2 and copied the code in SearchResults, which was previously unused.

**Review by Subhratanu — APPROVED** [review]
Approved & Merged @EmrysILIO1710 

Thanks!

**Pull request merged**
